spring:
  h2:         # H2 DATABASE
    console:
      enabled: true
      path: "/h2-console"
  datasource:
    url: "jdbc:h2:D:/Spring/han/chwijunjindan/chwijunjindanDB"
    driver-class-name: org.h2.Driver
    username: "sa"
    password:
  jpa:          # JPA
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"