== AI API (AiController)
=== AI 질의 실패(userId 없음)
==== 요청
operation::ai-controller-test/find-result-test1[snippets="http-request,request-fields"]
==== 응답
operation::ai-controller-test/find-result-test1[snippets="http-response,response-fields"]


=== AI 질의 실패(database 없음)
==== 요청
operation::ai-controller-test/find-result-test2[snippets="http-request,request-fields"]
==== 응답
operation::ai-controller-test/find-result-test2[snippets="http-response,response-fields"]

=== AI 질의 성공
==== 요청
operation::ai-controller-test/find-result-test3[snippets="http-request,request-fields"]
==== 응답
operation::ai-controller-test/find-result-test3[snippets="http-response,response-fields"]

=== AI 자기소개 질의 실패 (유효성 검사 실패)
==== 요청
operation::ai-controller-test/find-result-test4[snippets="http-request,request-fields"]
==== 응답
operation::ai-controller-test/find-result-test4[snippets="http-response,response-fields"]

=== AI 자기소개 질의 성공
==== 요청
operation::ai-controller-test/find-result-test5[snippets="http-request,request-fields"]
==== 응답
operation::ai-controller-test/find-result-test5[snippets="http-response,response-fields"]
