== 자격증 후기 작성 API (CertificationReviewController)
=== 게시글 리스트 조회
==== 요청
operation::certification-review-controller-test/get-post-list-test[snippets="http-request,path-parameters,query-parameters"]
==== 응답
operation::certification-review-controller-test/get-post-list-test[snippets="http-response,response-fields"]
=== 회원정보로 자격증 후기 리스트 조회
==== 요청
operation::certification-review-controller-test/get-post-list-by-user-account-test[snippets="http-request,path-parameters,query-parameters"]
==== 응답
operation::certification-review-controller-test/get-post-list-by-user-account-test[snippets="http-response,response-fields"]
=== 게시글 저장 실패
==== 요청
operation::certification-review-controller-test/save-post-fail-test[snippets="http-request,path-parameters,request-fields"]
==== 응답
operation::certification-review-controller-test/save-post-fail-test[snippets="http-response,response-fields"]
=== 게시글 저장 성공
==== 요청
operation::certification-review-controller-test/save-post-success-test[snippets="http-request,path-parameters,request-fields"]
==== 응답
operation::certification-review-controller-test/save-post-success-test[snippets="http-response,response-fields"]
=== 게시글 수정 실패
==== 요청
operation::certification-review-controller-test/update-post-fail-test[snippets="http-request,path-parameters,request-fields"]
==== 응답
operation::certification-review-controller-test/update-post-fail-test[snippets="http-response,response-fields"]
=== 게시글 수정 성공
==== 요청
operation::certification-review-controller-test/update-post-success-test[snippets="http-request,path-parameters,request-fields"]
==== 응답
operation::certification-review-controller-test/update-post-success-test[snippets="http-response,response-fields"]
=== 게시글 삭제 실패
==== 요청
operation::certification-review-controller-test/delete-post-fail-test[snippets="http-request,path-parameters,query-parameters"]
==== 응답
operation::certification-review-controller-test/delete-post-fail-test[snippets="http-response,response-fields"]
=== 게시글 삭제 성공
==== 요청
operation::certification-review-controller-test/delete-post-success-test[snippets="http-request,path-parameters,query-parameters"]
==== 응답
operation::certification-review-controller-test/delete-post-success-test[snippets="http-response,response-fields"]
