== 로그인 및 JWT API
=== 로그인 성공
==== 요청
operation::login-controller-test/login-success-test[snippets="http-request,form-parameters"]
==== 응답
operation::login-controller-test/login-success-test[snippets="http-response,response-fields"]
=== 로그인 실패 (사용자를 찾을 수 없음)
==== 요청
operation::login-controller-test/login-fail-test1[snippets="http-request,form-parameters"]
==== 응답
operation::login-controller-test/login-fail-test1[snippets="http-response,response-fields"]
=== 로그인 실패 (비밀번호가 맞지않음)
==== 요청
operation::login-controller-test/login-fail-test2[snippets="http-request,form-parameters"]
==== 응답
operation::login-controller-test/login-fail-test1[snippets="http-response,response-fields"]
'''
=== 액세스 확인 (유효한 엑세스 토큰)
==== 요청
operation::login-controller-test/valid-access-token-test[snippets="http-request,request-headers"]
==== 응답
operation::login-controller-test/valid-access-token-test[snippets="http-response"]
=== 액세스 확인 (유효하지 않은 엑세스 토큰)
==== 요청
operation::login-controller-test/invalid-access-token-test[snippets="http-request,request-headers"]
==== 응답
operation::login-controller-test/invalid-access-token-test[snippets="http-response"]
=== 리프레시 토큰 확인 (유효한 리프레시 토큰)
==== 요청
operation::login-controller-test/valid-refresh-token-test[snippets="http-request,request-headers"]
==== 응답
operation::login-controller-test/valid-refresh-token-test[snippets="http-response,response-fields"]
=== 리프레시 토큰 확인 (유효하지 않은 리프레시 토큰)
==== 요청
operation::login-controller-test/invalid-refresh-token-test[snippets="http-request,request-headers"]
==== 응답
operation::login-controller-test/invalid-refresh-token-test[snippets="http-response"]
=== 로그아웃
==== 요청
operation::login-controller-test/logout-test[snippets="http-request,request-headers"]
==== 응답
operation::login-controller-test/logout-test[snippets="http-response"]
