
== 커뮤니티 게시글 API (PostController)
=== 게시글 리스트 조회
==== 요청
operation::post-controller-test/get-post-list-test[snippets="http-request,query-parameters"]
==== 응답
operation::post-controller-test/get-post-list-test[snippets="http-response,response-fields"]
=== 게시글 리스트 조회 (사진 포함)
==== 요청
operation::post-controller-test/get-post-with-image-list-test[snippets="http-request,query-parameters"]
==== 응답
operation::post-controller-test/get-post-with-image-list-test[snippets="http-response,response-fields"]
=== 게시글 카테고리로 리스트 조회
==== 요청
operation::post-controller-test/get-post-list-by-category-test[snippets="http-request,query-parameters"]
==== 응답
operation::post-controller-test/get-post-list-by-category-test[snippets="http-response,response-fields"]
=== 게시글 회원정보로 리스트 조회
==== 요청
operation::post-controller-test/get-post-list-by-user-account-test[snippets="http-request,query-parameters"]
==== 응답
operation::post-controller-test/get-post-list-by-user-account-test[snippets="http-response,response-fields"]
=== 게시글 검색어로 검색
==== 요청
operation::post-controller-test/search-posts-test1[snippets="http-request,query-parameters"]
==== 응답
operation::post-controller-test/search-posts-test1[snippets="http-response,response-fields"]
=== 게시글 검색어와 카테고리로 검색
==== 요청
operation::post-controller-test/search-posts-test2[snippets="http-request,query-parameters"]
==== 응답
operation::post-controller-test/search-posts-test2[snippets="http-response,response-fields"]
=== 게시글 이미지 조회 (이미지 태그에 넣을 값)
==== 요청
operation::post-controller-test/get-image-resource-test[snippets="http-request,path-parameters"]
==== 응답
태그에 해당 url 을 넣으면 그에 해당하는 이미지 출력 (현재는 Mock 객체이기 때문에 없음)

=== 게시글 단건 조회
==== 요청
operation::post-controller-test/get-post-test[snippets="http-request,path-parameters"]
==== 응답
operation::post-controller-test/get-post-test[snippets="http-response,response-fields"]
=== 게시글 단건 조회 (사진 포함)
==== 요청
operation::post-controller-test/get-post-with-image-test[snippets="http-request,path-parameters"]
==== 응답
operation::post-controller-test/get-post-with-image-test[snippets="http-response,response-fields"]
=== 이미지 저장 요청
==== 요청
operation::post-controller-test/save-image-success-test[snippets="http-request"]
==== 응답
operation::post-controller-test/save-image-success-test[snippets="http-response,response-fields"]
=== 게시글 저장 실패
==== 요청
operation::post-controller-test/save-post-fail-test[snippets="http-request,request-fields"]
==== 응답
operation::post-controller-test/save-post-fail-test[snippets="http-response,response-fields"]
=== 게시글 저장 성공
==== 요청
operation::post-controller-test/save-post-success-test[snippets="http-request,request-fields"]
==== 응답
operation::post-controller-test/save-post-success-test[snippets="http-response,response-fields"]
=== 게시글 저장 성공 (사진 포함)
==== 요청
operation::post-controller-test/save-post-with-image-success-test[snippets="http-request,request-fields"]
==== 응답
operation::post-controller-test/save-post-with-image-success-test[snippets="http-response,response-fields"]
=== 게시글 수정 실패
==== 요청
operation::post-controller-test/update-post-fail-test[snippets="http-request,path-parameters,request-fields"]
==== 응답
operation::post-controller-test/update-post-fail-test[snippets="http-response,response-fields"]
=== 게시글 수정 성공
==== 요청
operation::post-controller-test/update-post-success-test[snippets="http-request,path-parameters,request-fields"]
==== 응답
operation::post-controller-test/update-post-success-test[snippets="http-response,response-fields"]
=== 게시글 삭제 실패
==== 요청
operation::post-controller-test/delete-post-fail-test[snippets="http-request,path-parameters,query-parameters"]
==== 응답
operation::post-controller-test/delete-post-fail-test[snippets="http-response,response-fields"]
=== 게시글 삭제 성공
==== 요청
operation::post-controller-test/delete-post-success-test[snippets="http-request,path-parameters,query-parameters"]
==== 응답
operation::post-controller-test/delete-post-success-test[snippets="http-response,response-fields"]

=== 공모전 검색조건으로 조회
==== 요청
operation::post-controller-test/search-posts-test[snippets="http-request,request-fields"]
==== 응답
operation::post-controller-test/search-posts-test[snippets="http-response,response-fields"]
=== 공모전 정보 조회 테스트
==== 요청
operation::post-controller-test/get-contest-test[snippets="http-request,path-parameters"]
==== 응답
operation::post-controller-test/search-posts-test[snippets="http-response,response-fields"]
=== 공모전 + 게시글 작성
==== 요청
operation::post-controller-test/save-contest-test[snippets="http-request,request-fields"]
==== 응답
operation::post-controller-test/search-posts-test[snippets="http-response,response-fields"]
=== 공모전 + 게시글 수정
==== 요청
operation::post-controller-test/update-contest-test[snippets="http-request,path-parameters,request-fields"]
==== 응답
operation::post-controller-test/update-contest-test[snippets="http-response,response-fields"]
=== 공모전 + 게시글 삭제
==== 요청
operation::post-controller-test/delete-contest-test[snippets="http-request,path-parameters,query-parameters"]
==== 응답
operation::post-controller-test/delete-contest-test[snippets="http-response,response-fields"]
