== 팀 매칭 API (TeamController)
=== UserId로 팀 기록 조회
==== 요청
operation::team-controller-test/find-by-user-id-test[snippets="http-request,path-parameters"]
==== 응답
operation::team-controller-test/find-by-user-id-test[snippets="http-response,response-fields"]
=== 팀 리스트 조회
==== 요청
operation::team-controller-test/find-all-test[snippets="http-request,query-parameters"]
==== 응답
operation::team-controller-test/find-all-test[snippets="http-response,response-fields"]
=== 팀 타입으로 리스트 조회
==== 요청
operation::team-controller-test/find-all-by-team-type-test[snippets="http-request,path-parameters,query-parameters"]
==== 응답
operation::team-controller-test/find-all-by-team-type-test[snippets="http-response,response-fields"]
=== 팀 세부정보 조회
==== 요청
operation::team-controller-test/find-by-team-id-test[snippets="http-request,path-parameters"]
==== 응답
operation::team-controller-test/find-by-team-id-test[snippets="http-response,response-fields"]
=== 팀 생성
==== 요청
operation::team-controller-test/make-team-test[snippets="http-request,request-fields"]
==== 응답
operation::team-controller-test/make-team-test[snippets="http-response,response-fields"]
=== 팀 수정
==== 요청
operation::team-controller-test/update-team-test[snippets="http-request,request-fields"]
==== 응답
operation::team-controller-test/update-team-test[snippets="http-response,response-fields"]
=== 팀 삭제
==== 요청
operation::team-controller-test/delete-team-test[snippets="http-request,request-fields"]
==== 응답
operation::team-controller-test/delete-team-test[snippets="http-response,response-fields"]
=== 팀 참가
==== 요청
operation::team-controller-test/join-team-test[snippets="http-request,request-fields"]
==== 응답
operation::team-controller-test/join-team-test[snippets="http-response,response-fields"]
=== 팀 떠나기
==== 요청
operation::team-controller-test/leave-team-test[snippets="http-request,request-fields"]
==== 응답
operation::team-controller-test/leave-team-test[snippets="http-response,response-fields"]
=== 팀원 추방
==== 요청
operation::team-controller-test/kick-member-test[snippets="http-request,request-fields"]
==== 응답
operation::team-controller-test/kick-member-test[snippets="http-response,response-fields"]
