== 회원가입 API (UserAccountController)
=== 회원가입 성공
==== 요청
operation::user-account-controller-test/register-test1[snippets="http-request,request-fields"]
==== 응답
operation::user-account-controller-test/register-test1[snippets="http-response,response-fields"]
=== 회원가입 중복 (id)
==== 요청
operation::user-account-controller-test/register-test2[snippets="http-request,request-fields"]
==== 응답
operation::user-account-controller-test/register-test2[snippets="http-response,response-fields"]
=== 회원가입 중복 (email)
==== 요청
operation::user-account-controller-test/register-test3[snippets="http-request,request-fields"]
==== 응답
operation::user-account-controller-test/register-test3[snippets="http-response,response-fields"]
=== 유효성 검사 통과 실패 (id)
==== 요청
operation::user-account-controller-test/register-test4[snippets="http-request,request-fields"]
==== 응답
operation::user-account-controller-test/register-test4[snippets="http-response,response-fields"]
=== 유효성 검사 통과 실패 (password)
==== 요청
operation::user-account-controller-test/register-test5[snippets="http-request,request-fields"]
==== 응답
operation::user-account-controller-test/register-test5[snippets="http-response,response-fields"]
=== 유효성 검사 통과 실패 (email)
==== 요청
operation::user-account-controller-test/register-test6[snippets="http-request,request-fields"]
==== 응답
operation::user-account-controller-test/register-test6[snippets="http-response,response-fields"]
=== 유효성 검사 통과 실패 (phoneNum)
==== 요청
operation::user-account-controller-test/register-test7[snippets="http-request,request-fields"]
==== 응답
operation::user-account-controller-test/register-test7[snippets="http-response,response-fields"]
=== 아이디 중복확인 (중복 X)
==== 요청
operation::user-account-controller-test/duplicate-check-id-success[snippets="http-request,path-parameters"]
==== 응답
operation::user-account-controller-test/duplicate-check-id-success[snippets="http-response,response-fields"]
=== 아이디 중복확인 (중복 O)
==== 요청
operation::user-account-controller-test/duplicate-check-id-fail[snippets="http-request,path-parameters"]
==== 응답
operation::user-account-controller-test/duplicate-check-id-fail[snippets="http-response,response-fields"]
=== 이메일 중복확인 (중복 X)
==== 요청
operation::user-account-controller-test/duplicate-check-email-success[snippets="http-request,path-parameters"]
==== 응답
operation::user-account-controller-test/duplicate-check-email-success[snippets="http-response,response-fields"]
=== 이메일 중복확인 (중복 O)
==== 요청
operation::user-account-controller-test/duplicate-check-email-fail[snippets="http-request,path-parameters"]
==== 응답
operation::user-account-controller-test/duplicate-check-email-fail[snippets="http-response,response-fields"]
=== 직무 추가 실패 (회원 정보를 찾을 수 없음)
==== 요청
operation::user-account-controller-test/add-career-fail-test[snippets="http-request,form-parameters"]
==== 응답
operation::user-account-controller-test/add-career-fail-test[snippets="http-response,response-fields"]
=== 직무 추가 성공
==== 요청
operation::user-account-controller-test/add-career-success-test[snippets="http-request,form-parameters"]
==== 응답
operation::user-account-controller-test/add-career-success-test[snippets="http-response,response-fields"]
=== 기술스택 추가 실패 (회원 정보를 찾을 수 없음)
==== 요청
operation::user-account-controller-test/add-stacks-fail-test[snippets="http-request,request-fields"]
==== 응답
operation::user-account-controller-test/add-stacks-fail-test[snippets="http-response,response-fields"]
=== 기술스택 추가 성공
==== 요청
operation::user-account-controller-test/add-stacks-success-test[snippets="http-request,request-fields"]
==== 응답
operation::user-account-controller-test/add-stacks-success-test[snippets="http-response,response-fields"]
