== 취득 자격증 API (UserCertificationController)
=== 취득 자격증 조회
==== 요청
operation::user-certification-controller-test/find-all-by-user-id-test[snippets="http-request,path-parameters"]
==== 응답
operation::user-certification-controller-test/find-all-by-user-id-test[snippets="http-response,response-fields"]
=== 취득 자격증 추가 실패 - userId 없음
==== 요청
operation::user-certification-controller-test/save-user-certification-test1[snippets="http-request,request-fields"]
==== 응답
operation::user-certification-controller-test/save-user-certification-test1[snippets="http-response,response-fields"]
=== 취득 자격증 추가 실패 - 자격증 이름 없음
==== 요청
operation::user-certification-controller-test/save-user-certification-test2[snippets="http-request,request-fields"]
==== 응답
operation::user-certification-controller-test/save-user-certification-test2[snippets="http-response,response-fields"]
=== 취득 자격증 추가 실패 - 취득일자 없음
==== 요청
operation::user-certification-controller-test/save-user-certification-test3[snippets="http-request,request-fields"]
==== 응답
operation::user-certification-controller-test/save-user-certification-test3[snippets="http-response,response-fields"]
=== 취득 자격증 추가 성공
==== 요청
operation::user-certification-controller-test/save-user-certification-test4[snippets="http-request,request-fields"]
==== 응답
operation::user-certification-controller-test/save-user-certification-test4[snippets="http-response,response-fields"]
